// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: StudyService.proto

package GrpcStudyService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ModuleId int32 `protobuf:"varint,2,opt,name=ModuleId,proto3" json:"ModuleId,omitempty"`
	Weight   int32 `protobuf:"varint,3,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Score    int32 `protobuf:"varint,4,opt,name=Score,proto3" json:"Score,omitempty"`
}

func (x *CreateUserRecordRequest) Reset() {
	*x = CreateUserRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StudyService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRecordRequest) ProtoMessage() {}

func (x *CreateUserRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_StudyService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRecordRequest) Descriptor() ([]byte, []int) {
	return file_StudyService_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRecordRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateUserRecordRequest) GetModuleId() int32 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *CreateUserRecordRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateUserRecordRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type CreateUserRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *CreateUserRecordResponse) Reset() {
	*x = CreateUserRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StudyService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRecordResponse) ProtoMessage() {}

func (x *CreateUserRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_StudyService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateUserRecordResponse) Descriptor() ([]byte, []int) {
	return file_StudyService_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRecordResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *GetUserRecordRequest) Reset() {
	*x = GetUserRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StudyService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRecordRequest) ProtoMessage() {}

func (x *GetUserRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_StudyService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRecordRequest.ProtoReflect.Descriptor instead.
func (*GetUserRecordRequest) Descriptor() ([]byte, []int) {
	return file_StudyService_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRecordRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserStudyRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Weight int32  `protobuf:"varint,4,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Score  int32  `protobuf:"varint,5,opt,name=Score,proto3" json:"Score,omitempty"`
}

func (x *UserStudyRecord) Reset() {
	*x = UserStudyRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StudyService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStudyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStudyRecord) ProtoMessage() {}

func (x *UserStudyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_StudyService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStudyRecord.ProtoReflect.Descriptor instead.
func (*UserStudyRecord) Descriptor() ([]byte, []int) {
	return file_StudyService_proto_rawDescGZIP(), []int{3}
}

func (x *UserStudyRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserStudyRecord) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UserStudyRecord) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetUserRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserRecord []*UserStudyRecord `protobuf:"bytes,1,rep,name=UserRecord,proto3" json:"UserRecord,omitempty"`
}

func (x *GetUserRecordResponse) Reset() {
	*x = GetUserRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StudyService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRecordResponse) ProtoMessage() {}

func (x *GetUserRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_StudyService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRecordResponse.ProtoReflect.Descriptor instead.
func (*GetUserRecordResponse) Descriptor() ([]byte, []int) {
	return file_StudyService_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRecordResponse) GetUserRecord() []*UserStudyRecord {
	if x != nil {
		return x.UserRecord
	}
	return nil
}

var File_StudyService_proto protoreflect.FileDescriptor

var file_StudyService_proto_rawDesc = []byte{
	0x0a, 0x12, 0x53, 0x74, 0x75, 0x64, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x22, 0x32, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x75,
	0x64, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x49, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x75, 0x64, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x32, 0x97, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x75, 0x64, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x47, 0x72, 0x70, 0x63, 0x53, 0x74, 0x75, 0x64, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_StudyService_proto_rawDescOnce sync.Once
	file_StudyService_proto_rawDescData = file_StudyService_proto_rawDesc
)

func file_StudyService_proto_rawDescGZIP() []byte {
	file_StudyService_proto_rawDescOnce.Do(func() {
		file_StudyService_proto_rawDescData = protoimpl.X.CompressGZIP(file_StudyService_proto_rawDescData)
	})
	return file_StudyService_proto_rawDescData
}

var file_StudyService_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_StudyService_proto_goTypes = []interface{}{
	(*CreateUserRecordRequest)(nil),  // 0: CreateUserRecordRequest
	(*CreateUserRecordResponse)(nil), // 1: CreateUserRecordResponse
	(*GetUserRecordRequest)(nil),     // 2: GetUserRecordRequest
	(*UserStudyRecord)(nil),          // 3: UserStudyRecord
	(*GetUserRecordResponse)(nil),    // 4: GetUserRecordResponse
}
var file_StudyService_proto_depIdxs = []int32{
	3, // 0: GetUserRecordResponse.UserRecord:type_name -> UserStudyRecord
	2, // 1: StudyService.GetUserRecord:input_type -> GetUserRecordRequest
	0, // 2: StudyService.CreateUserRecord:input_type -> CreateUserRecordRequest
	4, // 3: StudyService.GetUserRecord:output_type -> GetUserRecordResponse
	1, // 4: StudyService.CreateUserRecord:output_type -> CreateUserRecordResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_StudyService_proto_init() }
func file_StudyService_proto_init() {
	if File_StudyService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_StudyService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StudyService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StudyService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StudyService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStudyRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StudyService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_StudyService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_StudyService_proto_goTypes,
		DependencyIndexes: file_StudyService_proto_depIdxs,
		MessageInfos:      file_StudyService_proto_msgTypes,
	}.Build()
	File_StudyService_proto = out.File
	file_StudyService_proto_rawDesc = nil
	file_StudyService_proto_goTypes = nil
	file_StudyService_proto_depIdxs = nil
}
