// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	CreateUserPassword(ctx context.Context, arg CreateUserPasswordParams) error
	DeleteUser(ctx context.Context, id int32) error
	DeleteUserPassword(ctx context.Context, userID int32) error
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserPassword(ctx context.Context, userID int32) (UserPassword, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
